from copy import deepcopy
from random import choice, randint, shuffle, uniform


EPSILON = 1e-12


class Gene(object):
    """
    Represents the gene configuration used to build chromosomes.

    A gene defines:
    - the interval or set of possible values;
    - the value type;
    - the number of decimal places used for float values.
    """

    def __init__(
        self,
        gene_space=(),
        value_type="I",
        decimal_places=0
    ):
        """
        Initialize a gene.

        Parameters
        ----------
        gene_space : tuple
            Interval or discrete set of possible values.
            Examples:
            - (0, 1) for an integer interval
            - (0, 1, 2) for a discrete action set

        value_type : str
            Type of value generated by the gene.
            Use "F" for float values.
            Use "I" for integer or discrete values.

        decimal_places : int
            Number of decimal places used when generating float values.
        """

        self.gene_space = gene_space
        self.value_type = value_type
        self.decimal_places = decimal_places

    def get_gene_space(self):
        """
        Return the gene value interval or discrete value set.
        """

        return self.gene_space

    def get_value_type(self):
        """
        Return the gene value type.
        """

        return self.value_type

    def get_decimal_places(self):
        """
        Return the number of decimal places used for float values.
        """

        return self.decimal_places

    def set_gene_space(self, gene_space, value_type=None):
        """
        Update the gene interval or discrete value set.
        """

        self.gene_space = gene_space

        if value_type is not None:
            self.value_type = value_type


class Chromosome(object):
    """
    Represents one chromosome in the genetic algorithm population.

    Each chromosome contains:
    - a sequence of gene values;
    - a score/fitness value;
    - a maximum size;
    - a mutation probability.
    """

    def __init__(
        self,
        gene,
        max_size=2000,
        chromosome_string=None,
        score=0,
        mutation_rate=5
    ):
        """
        Initialize a chromosome.

        Parameters
        ----------
        gene : Gene
            Gene configuration used to generate chromosome values.

        max_size : int
            Number of values in the chromosome.

        chromosome_string : list, optional
            Existing chromosome values. If None, an empty list is used.

        score : float
            Fitness score of the chromosome.

        mutation_rate : float
            Mutation probability in percentage.
            Example: 5 means 5%.
        """

        if chromosome_string is None:
            chromosome_string = []

        self.chromosome_string = chromosome_string
        self.score = score
        self.max_size = max_size
        self.gene = gene
        self.mutation_rate = mutation_rate

    def get_string(self):
        """
        Return the chromosome string.
        """

        return self.chromosome_string

    def get_mutation_rate(self):
        """
        Return the mutation probability.
        """

        return self.mutation_rate

    def get_score(self):
        """
        Return the chromosome score.
        """

        return self.score

    def get_max_size(self):
        """
        Return the maximum chromosome size.
        """

        return self.max_size

    def get_gene(self):
        """
        Return the gene configuration used by this chromosome.
        """

        return self.gene

    def set_score(self, score):
        """
        Set the chromosome score.
        """

        self.score = score

    def generate_random_value(self):
        """
        Generate one random value according to the gene configuration.

        Returns
        -------
        int or float
            Random value generated from the gene space.
        """

        gene_space = self.get_gene().get_gene_space()
        value_type = self.get_gene().get_value_type()
        decimal_places = self.get_gene().get_decimal_places()

        if len(gene_space) == 0:
            raise ValueError(
                "Cannot generate a value from an empty gene space."
            )

        # Float interval
        if value_type == "F":
            minimum_value = gene_space[0]
            maximum_value = gene_space[1]

            return round(
                uniform(minimum_value, maximum_value),
                decimal_places
            )

        # Integer interval, for example: (0, 2)
        if value_type == "I" and len(gene_space) == 2:
            return randint(
                gene_space[0],
                gene_space[1]
            )

        # Discrete value set, for example: (0, 1, 2)
        return choice(gene_space)

    @staticmethod
    def fill_random_chromosome(chromosome):
        """
        Fill an empty chromosome with random values.

        Parameters
        ----------
        chromosome : Chromosome
            Chromosome to be filled.

        Returns
        -------
        Chromosome
            Filled chromosome.
        """

        if len(chromosome.get_string()) == 0:
            chromosome_string = []

            for _ in range(chromosome.get_max_size()):
                chromosome_string.append(
                    chromosome.generate_random_value()
                )

            chromosome.chromosome_string = chromosome_string

        return chromosome

    def crossover(self, other_chromosome):
        """
        Perform uniform crossover between two chromosomes.

        Each position of the offspring chromosomes receives a value
        randomly chosen from one of the parent chromosomes.

        Parameters
        ----------
        other_chromosome : Chromosome
            Second parent chromosome.

        Returns
        -------
        tuple
            Two new chromosome strings generated by crossover.
        """

        first_child_string = []
        second_child_string = []

        for i in range(self.get_max_size()):
            random_choice = randint(0, 1)

            if random_choice == 1:
                first_child_string.append(
                    deepcopy(self.get_string()[i])
                )
                second_child_string.append(
                    deepcopy(other_chromosome.get_string()[i])
                )
            else:
                first_child_string.append(
                    deepcopy(other_chromosome.get_string()[i])
                )
                second_child_string.append(
                    deepcopy(self.get_string()[i])
                )

        # Apply mutation to the first child
        if uniform(0, 100) <= self.get_mutation_rate():
            mutation_index = choice(range(self.get_max_size()))

            first_child_string[mutation_index] = (
                self.generate_random_value()
            )

        # Apply mutation to the second child
        if uniform(0, 100) <= self.get_mutation_rate():
            mutation_index = choice(range(self.get_max_size()))

            second_child_string[mutation_index] = (
                self.generate_random_value()
            )

        return first_child_string, second_child_string

    def __str__(self):
        """
        Return a readable representation of the chromosome.
        """

        return "\nScore: " + str(self.get_score())

    def __eq__(self, other_chromosome):
        """
        Compare chromosomes by their strings.
        """

        return self.get_string() == other_chromosome.get_string()

    def __lt__(self, other_chromosome):
        """
        Compare chromosomes by score.

        This allows using max() and min() directly on chromosomes.
        """

        return self.get_score() < other_chromosome.get_score()


class GeneticMachine(object):
    """
    Represents the genetic algorithm engine.

    It stores the population and applies:
    - tournament selection;
    - roulette selection;
    - elitism;
    - crossover;
    - mutation;
    - generation updates.
    """

    def __init__(
        self,
        gene,
        max_size=-1,
        population=None,
        size=50,
        selection_probability=40,
        elitism=10
    ):
        """
        Initialize the genetic machine.

        Parameters
        ----------
        gene : Gene
            Gene configuration used by the population.

        max_size : int
            Chromosome size.

        population : list, optional
            Initial population.

        size : int
            Population size.

        selection_probability : float
            Probability of selecting the best chromosome in a tournament.

        elitism : float
            Percentage of the best chromosomes preserved unchanged.
            Example: 10 means 10%.
        """

        if population is None:
            population = []

        self.population = population
        self.size = size
        self.generation = 0
        self.gene = gene
        self.selection_probability = selection_probability
        self.max_size = max_size
        self.elitism = elitism

    def get_population(self):
        """
        Return the current population.
        """

        return self.population

    def get_max_size(self):
        """
        Return the chromosome size used by the genetic machine.
        """

        return self.max_size

    def get_selection_probability(self):
        """
        Return the tournament selection probability.
        """

        return self.selection_probability

    def get_elitism(self):
        """
        Return the elitism percentage.
        """

        return self.elitism

    def get_size(self):
        """
        Return the population size.
        """

        return self.size

    def get_generation(self):
        """
        Return the current generation number.
        """

        return self.generation

    def get_gene(self):
        """
        Return the gene configuration.
        """

        return self.gene

    def set_generation(self, generation):
        """
        Set the current generation number.
        """

        self.generation = generation

    def add(self, chromosome):
        """
        Add one chromosome to the population.

        If this is the first chromosome added, its size is used as
        the default chromosome size of the genetic machine.
        """

        self.population.append(chromosome)

        if len(self.get_population()) == 1:
            self.max_size = self.get_population()[0].get_max_size()

    def get_elite_count(self):
        """
        Return how many chromosomes should be preserved by elitism.
        """

        return int(
            (self.get_elitism() / 100)
            * self.get_size()
        )

    def get_elites(self):
        """
        Return the best chromosomes preserved by elitism.

        Since Chromosome.__lt__ compares by score, sorting the population
        places weaker chromosomes first and stronger chromosomes last.
        """

        elite_count = self.get_elite_count()

        if elite_count <= 0:
            return []

        sorted_population = sorted(self.get_population())

        return sorted_population[-elite_count:]

    def clone_chromosome(self, chromosome):
        """
        Create a copy of a chromosome.

        This avoids accidental reference sharing when replacing weak
        individuals or preserving elites.
        """

        return Chromosome(
            chromosome.get_gene(),
            chromosome.get_max_size(),
            deepcopy(chromosome.get_string()),
            chromosome.get_score(),
            chromosome.get_mutation_rate()
        )

    def adapt_population(self, pool_size=None):
        """
        Apply tournament selection to create a parent list.

        Two chromosomes are randomly selected.
        With a given probability, the best one is chosen.
        Otherwise, the worst one is chosen.

        Parameters
        ----------
        pool_size : int, optional
            Number of selected parents. If None, population size is used.

        Returns
        -------
        list
            List of selected chromosomes.
        """

        if pool_size is None:
            pool_size = self.get_size()

        selected_chromosomes = []

        selection_probability = (
            self.get_selection_probability() / 100
        )

        for _ in range(pool_size):
            first_chromosome = choice(self.get_population())
            second_chromosome = choice(self.get_population())

            random_probability = uniform(0, 1)

            if random_probability <= selection_probability:
                selected_chromosomes.append(
                    max(first_chromosome, second_chromosome)
                )
            else:
                selected_chromosomes.append(
                    min(first_chromosome, second_chromosome)
                )

        return selected_chromosomes

    def roulette_selection_index(self, inverse_score=False):
        """
        Select one chromosome index using roulette selection.

        Parameters
        ----------
        inverse_score : bool
            If False, larger scores receive larger probability.
            Use this for accuracy, reward, or positive fitness.

            If True, smaller absolute scores receive larger probability.
            Use this when your score represents error, for example -error
            or values close to zero being better.

        Returns
        -------
        int
            Selected chromosome index.
        """

        population = self.get_population()

        if len(population) == 0:
            raise ValueError("Cannot select from an empty population.")

        scores = [
            chromosome.get_score()
            for chromosome in population
        ]

        weights = []

        if inverse_score:
            # Useful when values closer to zero are better.
            # Example: score = -error.
            for score in scores:
                weights.append(
                    1 / (abs(score) + EPSILON)
                )
        else:
            # Useful when larger score is better.
            # Shift values to avoid negative probabilities.
            minimum_score = min(scores)

            for score in scores:
                weights.append(
                    score - minimum_score + EPSILON
                )

        total_weight = sum(weights)

        if total_weight <= 0:
            return randint(0, len(population) - 1)

        random_number = uniform(0, total_weight)
        accumulated_weight = 0

        for index, weight in enumerate(weights):
            accumulated_weight += weight

            if random_number <= accumulated_weight:
                return index

        return len(population) - 1

    def roulette_select_chromosome(self, inverse_score=False):
        """
        Return one chromosome selected by roulette.
        """

        selected_index = self.roulette_selection_index(
            inverse_score=inverse_score
        )

        return self.get_population()[selected_index]

    def create_children_from_parents(
        self,
        parent_pool,
        number_of_children
    ):
        """
        Create children from a parent pool using crossover.

        Parameters
        ----------
        parent_pool : list
            List of chromosomes available as parents.

        number_of_children : int
            Number of children to generate.

        Returns
        -------
        list
            List of new chromosomes.
        """

        children = []

        if len(parent_pool) == 0:
            raise ValueError("Parent pool cannot be empty.")

        while len(children) < number_of_children:
            first_parent = choice(parent_pool)
            second_parent = choice(parent_pool)

            first_child_string, second_child_string = (
                first_parent.crossover(second_parent)
            )

            first_child = Chromosome(
                self.get_gene(),
                self.get_max_size(),
                first_child_string,
                score=0,
                mutation_rate=first_parent.get_mutation_rate()
            )

            second_child = Chromosome(
                self.get_gene(),
                self.get_max_size(),
                second_child_string,
                score=0,
                mutation_rate=second_parent.get_mutation_rate()
            )

            children.append(first_child)

            if len(children) < number_of_children:
                children.append(second_child)

        return children

    def selection_by_tournament_without_elitism(self):
        """
        Apply tournament selection without elitism.

        This is close to the original selection behavior.
        """

        selected_chromosomes = self.adapt_population(
            pool_size=self.get_size()
        )

        new_population = self.create_children_from_parents(
            selected_chromosomes,
            self.get_size()
        )

        self.population = new_population

        self.set_generation(
            self.get_generation() + 1
        )

    def selection_by_tournament_with_elitism(self):
        """
        Apply tournament selection with elitism.

        The best chromosomes are preserved unchanged.
        The rest of the population is generated by crossover and mutation.
        """

        elites = [
            self.clone_chromosome(chromosome)
            for chromosome in self.get_elites()
        ]

        number_of_children = self.get_size() - len(elites)

        selected_chromosomes = self.adapt_population(
            pool_size=max(number_of_children, 2)
        )

        children = self.create_children_from_parents(
            selected_chromosomes,
            number_of_children
        )

        self.population = elites + children

        shuffle(self.population)

        self.set_generation(
            self.get_generation() + 1
        )

    def selection_by_roulette_with_elitism(self, inverse_score=False):
        """
        Apply roulette selection with elitism.

        Parameters
        ----------
        inverse_score : bool
            If False, larger scores have higher selection probability.
            If True, scores closer to zero have higher probability.
        """

        elites = [
            self.clone_chromosome(chromosome)
            for chromosome in self.get_elites()
        ]

        number_of_children = self.get_size() - len(elites)

        parent_pool = []

        for _ in range(max(number_of_children, 2)):
            parent_pool.append(
                self.roulette_select_chromosome(
                    inverse_score=inverse_score
                )
            )

        children = self.create_children_from_parents(
            parent_pool,
            number_of_children
        )

        self.population = elites + children

        shuffle(self.population)

        self.set_generation(
            self.get_generation() + 1
        )

    def replace_weak_individuals(self, replacement_percentage=None):
        """
        Experimental method for replacing weak chromosomes.

        This does not perform crossover. It only replaces part of the
        weakest non-elite group with copies of stronger chromosomes.

        Parameters
        ----------
        replacement_percentage : float, optional
            Percentage of non-elite chromosomes to replace.
            If None, selection_probability is used.
        """

        if replacement_percentage is None:
            replacement_percentage = self.get_selection_probability()

        elite_count = self.get_elite_count()

        sorted_population = sorted(self.get_population())

        if elite_count > 0:
            non_elites = sorted_population[:-elite_count]
            elites = sorted_population[-elite_count:]
        else:
            non_elites = sorted_population
            elites = []

        if len(non_elites) == 0:
            return

        replacement_count = int(
            (replacement_percentage / 100)
            * len(non_elites)
        )

        if replacement_count <= 0:
            return

        strong_pool = non_elites[replacement_count:] + elites

        if len(strong_pool) == 0:
            return

        for i in range(replacement_count):
            non_elites[i] = self.clone_chromosome(
                choice(strong_pool)
            )

        self.population = non_elites + elites

        shuffle(self.population)

    def selection(self, method="tournament_elitism"):
        """
        Apply genetic selection.

        Available methods
        -----------------
        "tournament_elitism"
            Tournament selection with elitism.
            Recommended default for most experiments.

        "tournament"
            Tournament selection without elitism.
            Similar to the original implementation.

        "roulette"
            Roulette selection with elitism.
            Use when larger scores are better.

        "roulette_inverse"
            Roulette selection with elitism using inverse absolute score.
            Use when scores closer to zero are better, such as -error.
        """

        if method == "tournament_elitism":
            self.selection_by_tournament_with_elitism()

        elif method == "tournament":
            self.selection_by_tournament_without_elitism()

        elif method == "roulette":
            self.selection_by_roulette_with_elitism(
                inverse_score=False
            )

        elif method == "roulette_inverse":
            self.selection_by_roulette_with_elitism(
                inverse_score=True
            )

        else:
            raise ValueError(
                "Unknown selection method: " + str(method)
            )

    def __str__(self):
        """
        Return a readable representation of the current generation.
        """

        return "Generation: " + str(self.get_generation())


# Recommended usage:
#
# genetic_machine.selection()
#
# This uses tournament selection with elitism by default.
#
#
# Other options:
#
# genetic_machine.selection(method="tournament")
# genetic_machine.selection(method="roulette")
# genetic_machine.selection(method="roulette_inverse")
#
#
# Use "roulette_inverse" when your score is based on error,
# for example:
#
# score = -error